name: "commit-master"

on:
  push:
    branches: 
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    - name: check docker version
      run: docker -v
      
    # docker login,设置登陆到华为的swr
    - name: Login to huawei SWR
      uses: docker/login-action@v1
      with:
        registry: "swr.cn-north-4.myhuaweicloud.com"
        username: ${{ secrets.SWR_USERNAME }}
        password: ${{ secrets.SWR_PASSWD }}

    # 设置 docker 环境
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    # build 并且 push docker 镜像
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: swr.cn-north-4.myhuaweicloud.com/ptworkflow/tomcat:maven-sample

    # 打印 docker 镜像 SHA256 Hash 值
#    - name: Image digest
#      run: echo ${{ steps.docker_build.outputs.digest }}

    # 安装sshpass
    - name: install sshpass
      run: sudo apt-get -y update && sudo apt-get install -y sshpass

    #一键安装docker
    #使用官方的安装脚本进行安装，脚本地址为https://get.docker.com/ 
    #官方的安装脚本在执行yum makecache的时候可能出现 Exiting on user cancel报错,请关注官方的解决方案，或者纯手工进行安装
    
    # 在目标机器上安装docker,如果docker已经安装好,可以将这一步骤注释
#    - name: install docker on server
#      run |
#        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "curl -sSL https://get.docker.com/ | sh"

    # 在目标机器上安装docker,如果无法下载脚本，可以使用这个脚本
#    - name: install docker on server by install-docker.sh
#      run |
#        sshpass -p ${{ secrets.CCE_PASSWORD }}  scp  -o StrictHostKeyChecking=no root@182.92.156.203 "sh /tmp/install-docker.sh"
#        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "systemctl enable docker.service && systemctl start docker.service && docker -v"

    # 在目标机器上安装docker,如果docker已经安装好,可以将这一步骤注释
#    - name: enable and start docker on server
#      run |
#        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "systemctl enable docker.service && systemctl start docker.service && docker -v"     
        
    # 下载镜像并启动服务
    - name: pull image and start server
      run: |
        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "docker stop \$(docker ps -a -q)"
        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "docker rm \$(docker ps -a -q)"
        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "docker pull swr.cn-north-4.myhuaweicloud.com/ptworkflow/tomcat:maven-sample"
        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "docker run -d -p 8080:8080 swr.cn-north-4.myhuaweicloud.com/ptworkflow/tomcat:maven-sample"
        sleep 30
        sshpass -p ${{ secrets.CCE_PASSWORD }}  ssh -o StrictHostKeyChecking=no root@182.92.156.203 "docker ps | grep tomcat"
        curl -kv http://182.92.156.203:8080/intro/index.html